// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: removeAllUsers.sql

package database

import (
	"context"
)

const deleteAllUsers = `-- name: DeleteAllUsers :exec
DELETE FROM users
`

// DEV ONLY: deletes all user rows without touching schema
func (q *Queries) DeleteAllUsers(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, deleteAllUsers)
	return err
}
